#! /bin/bash

# Create a basic config
lb config noauto -d squeeze -a i386 -p "gnome" -m http://ftp.uk.debian.org/debian/ --net-root-path /srv/tftp/competitor-client --net-root-server 172.19.0.1 --bootappend-live "live-config.noroot" -b net

# Add the udev rule to hide disks
mkdir -p config/includes.chroot/etc/udev/rules.d/
cat <<EOF > config/includes.chroot/etc/udev/rules.d/999-hide-local-disks.rules
SUBSYSTEMS=="usb", GOTO="sr_is_usb_mass_storage_device"

ACTION=="add|change", SUBSYSTEM=="block", ENV{UDISKS_AUTOMOUNT_HINT}="never", ENV{UDISKS_PRESENTATION_HIDE}="1"

LABEL="sr_is_usb_mass_storage_device"
EOF

# Add the set-root-password boot task
mkdir -p config/includes.chroot/lib/live/config/
cat <<EOF > config/includes.chroot/lib/live/config/999-set-root-password
#! /bin/bash

# Set root's password on the target system
sed -ri 's|^root(.*)$|root:\$6\$ib9QZokx\$tP4h4YXGaWIpIcRS8Vw1FS.FF1xbwzOckAc3etiMekeYFNqFDKhA01/ajTdXF6nDGjvcsiRthRko2lJ7v.xJr1:15379:0:99999:7:::|' /etc/shadow
EOF
chmod +x config/includes.chroot/lib/live/config/999-set-root-password

# Add extra packages 
mkdir -p config/package-lists/
cat <<EOF >config/package-lists/sr-extra-apps.list.chroot
git-core
vim
geany
chromium-browser
python-serial
python-usb
python-yaml
python-opencv
python-cairo
python-gtk2
EOF

# Make the system log out of the competition network on shutdown.....
mkdir -p config/includes.chroot/etc/init.d/
mkdir -p config/includes.chroot/etc/rc0.d/
mkdir -p config/includes.chroot/etc/rc1.d/
mkdir -p config/includes.chroot/etc/rc2.d/
mkdir -p config/includes.chroot/etc/rc3.d/
mkdir -p config/includes.chroot/etc/rc4.d/
mkdir -p config/includes.chroot/etc/rc5.d/
mkdir -p config/includes.chroot/etc/rc6.d/

cat > config/includes.chroot/etc/init.d/sr-network-logout <<EOF
#! /bin/sh
### BEGIN INIT INFO
# Provides:          sr-network-logout
# Required-Start:    \$local_fs \$remote_fs \$network \$syslog \$named
# Required-Stop:     \$local_fs \$remote_fs \$network \$syslog \$named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Log out of the SR network on shutdown
### END INIT INFO


case "\$1" in
	start)
		/usr/bin/wget -q -O /dev/null http://auth.net.studentrobotics.org/deauth_client.php
		;;
	stop)
		/usr/bin/wget -q -O /dev/null http://auth.net.studentrobotics.org/deauth_client.php
		;;
esac
EOF
chmod +x config/includes.chroot/etc/init.d/sr-network-logout
pushd config/includes.chroot/etc/rc0.d/ && ln -s ../init.d/sr-network-logout K01sr-network-logout && popd
pushd config/includes.chroot/etc/rc1.d/ && ln -s ../init.d/sr-network-logout K01sr-network-logout && popd
pushd config/includes.chroot/etc/rc2.d/ && ln -s ../init.d/sr-network-logout S01sr-network-logout && popd
pushd config/includes.chroot/etc/rc3.d/ && ln -s ../init.d/sr-network-logout S01sr-network-logout && popd
pushd config/includes.chroot/etc/rc4.d/ && ln -s ../init.d/sr-network-logout S01sr-network-logout && popd
pushd config/includes.chroot/etc/rc5.d/ && ln -s ../init.d/sr-network-logout S01sr-network-logout && popd
pushd config/includes.chroot/etc/rc6.d/ && ln -s ../init.d/sr-network-logout K01sr-network-logout && popd

