#! /bin/bash

# Create a basic config
lb config noauto -d squeeze -a i386 -p "gnome" -m http://ftp.uk.debian.org/debian/ --net-root-path /srv/tftp/competitor-client --net-root-server 172.19.0.1 --bootappend-live "live-config.noroot" -b net

# Add the udev rule to hide disks
mkdir -p config/includes.chroot/etc/udev/rules.d/
cat <<EOF > config/includes.chroot/etc/udev/rules.d/999-hide-local-disks.rules
SUBSYSTEMS=="usb", GOTO="sr_is_usb_mass_storage_device"

ACTION=="add|change", SUBSYSTEM=="block", ENV{UDISKS_AUTOMOUNT_HINT}="never", ENV{UDISKS_PRESENTATION_HIDE}="1"

LABEL="sr_is_usb_mass_storage_device"
EOF

# Add the set-root-password boot task
mkdir -p config/includes.chroot/lib/live/config/
cat <<EOF > config/includes.chroot/lib/live/config/999-set-root-password
#! /bin/bash

# Set root's password on the target system
sed -ri 's|^root(.*)$|root:\$6\$ib9QZokx\$tP4h4YXGaWIpIcRS8Vw1FS.FF1xbwzOckAc3etiMekeYFNqFDKhA01/ajTdXF6nDGjvcsiRthRko2lJ7v.xJr1:15379:0:99999:7:::|' /etc/shadow
EOF
chmod +x config/includes.chroot/lib/live/config/999-set-root-password

# Add extra packages 
mkdir -p config/package-lists/
cat <<EOF >config/package-lists/sr-extra-apps.list.chroot
git-core
vim
geany
chromium-browser
python-serial
python-usb
python-yaml
python-opencv
python-cairo
python-gtk2
EOF

# Make the system log out of the competition network on shutdown.....
mkdir -p config/includes.chroot/etc/rc0.d/
cat > config/includes.chroot/etc/rc0.d/K01sr-network-logout <<EOF
#! /bin/sh
wget -q -O /dev/null http://auth.net.studentrobotics.org/deauth_client.php
EOF
chmod +x config/includes.chroot/etc/rc0.d/K01sr-network-logout
